// src/views/calculators/LongMultiplicationCalculator.vue
<template>
  <div class="calculator-page">
    <Navbar />
    
    <div class="page-background">
      <div class="bg-gradient"></div>
    </div>

    <div class="container">
      <div class="calculator-header">
        <router-link :to="$i18n.locale === 'en' ? '/' : `/${$i18n.locale}/`" class="back-button">
          <svg class="back-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M15 18L9 12L15 6" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          <span>{{ $t('common.back') }}</span>
        </router-link>
        <div class="header-content">
          <div class="title-badge">{{ $t('calculators.longMultiplication.badge') }}</div>
          <h1 class="page-title">{{ $t('calculators.longMultiplication.title') }}</h1>
          <p class="page-description">{{ $t('calculators.longMultiplication.description') }}</p>
        </div>
      </div>

      <div class="calculator-container">
        <div class="calculator-card">
          <!-- Input Section -->
          <div class="input-section">
            <div class="input-row">
              <div class="input-card">
                <label class="input-label">{{ $t('calculators.longMultiplication.firstNumber') }}</label>
                <input
                  v-model.number="number1"
                  type="number"
                  class="number-input"
                  :placeholder="$t('calculators.longMultiplication.placeholder')"
                  @input="validateInput"
                  @keyup.enter="calculate"
                  step="1"
                />
              </div>
              
              <div class="input-card">
                <label class="input-label">{{ $t('calculators.longMultiplication.secondNumber') }}</label>
                <input
                  v-model.number="number2"
                  type="number"
                  class="number-input"
                  :placeholder="$t('calculators.longMultiplication.placeholder')"
                  @input="validateInput"
                  @keyup.enter="calculate"
                  step="1"
                />
              </div>
            </div>

            <!-- Action Buttons -->
            <div class="action-buttons">
              <button @click="calculate" class="btn btn-primary" :disabled="!canCalculate">
                <svg class="btn-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M5 12H19M19 12L12 5M19 12L12 19" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
                <span>{{ $t('calculators.longMultiplication.calculate') }}</span>
              </button>
              <button @click="clear" class="btn btn-secondary">
                <svg class="btn-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M18 6L6 18M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
                <span>{{ $t('calculators.longMultiplication.clear') }}</span>
              </button>
            </div>
          </div>

          <!-- Error Message -->
          <transition name="slide-down">
            <div v-if="error" class="error-message">
              <svg class="error-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2"/>
                <path d="M12 8V12M12 16H12.01" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
              </svg>
              <span>{{ error }}</span>
            </div>
          </transition>

          <!-- Result Section -->
          <transition name="slide-up">
            <div v-if="result !== null" class="result-section">
              <div class="result-header">
                <div class="result-badge">
                  <svg class="result-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M9 12L11 14L15 10M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                  </svg>
                  {{ $t('calculators.longMultiplication.result') }}
                </div>
              </div>

              <div class="result-display">
                <div class="multiplication-result">
                  <div class="result-formula">
                    <span class="formula-text">{{ number1 }} × {{ number2 }}</span>
                    <span class="equals-sign">=</span>
                  </div>
                  <div class="result-value-box">
                    <span class="result-value">{{ result }}</span>
                  </div>
                </div>
              </div>

              <!-- Long Multiplication Steps -->
              <div v-if="multiplicationSteps.length > 0" class="multiplication-steps-section">
                <div class="steps-header">
                  <svg class="steps-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M9 11L12 14L22 4M21 12V19C21 19.5304 20.7893 20.0391 20.4142 20.4142C20.0391 20.7893 19.5304 21 19 21H5C4.46957 21 3.96086 20.7893 3.58579 20.4142C3.21071 20.0391 3 19.5304 3 19V5C3 4.46957 3.21071 3.96086 3.58579 3.58579C3.96086 3.21071 4.46957 3 5 3H16" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                  </svg>
                  <h4 class="steps-title">{{ $t('calculators.longMultiplication.stepByStep') }}</h4>
                </div>

                <!-- Multiplication Visualization -->
                <div class="multiplication-visualization">
                  <div class="multiplication-line" v-for="(step, index) in multiplicationSteps" :key="index">
                    <div class="step-number">{{ index + 1 }}</div>
                    <div class="step-content">
                      <div class="multiplication-display" v-html="step.display"></div>
                      <div class="step-explanation">{{ step.explanation }}</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </transition>
        </div>

        <!-- SEO Content Section -->
        <div class="seo-content-section">
          <div class="seo-content-card">
            <h2 class="seo-heading">{{ $t('calculators.longMultiplication.seo.content.heading') }}</h2>
            
            <div class="seo-paragraphs">
              <p class="seo-paragraph">
                {{ $t('calculators.longMultiplication.seo.content.paragraph1') }}
              </p>
              
              <p class="seo-paragraph">
                {{ $t('calculators.longMultiplication.seo.content.paragraph2') }}
              </p>
              
              <p class="seo-paragraph">
                {{ $t('calculators.longMultiplication.seo.content.paragraph3') }}
              </p>
              
              <div class="seo-example">
                <h3 class="example-heading">{{ $t('calculators.longMultiplication.seo.content.exampleHeading') }}</h3>
                <p class="example-text">{{ $t('calculators.longMultiplication.seo.content.exampleText') }}</p>
              </div>
              
              <p class="seo-paragraph">
                {{ $t('calculators.longMultiplication.seo.content.paragraph4') }}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Navbar from '../../components/Navbar.vue'
import { updateHreflangTags, updateCanonicalTag } from '../../utils/seo.js'
import { supportedLocales } from '../../router/index.js'

export default {
  name: 'LongMultiplicationCalculator',
  components: {
    Navbar
  },
  data() {
    return {
      number1: null,
      number2: null,
      result: null,
      error: '',
      multiplicationSteps: []
    }
  },
  computed: {
    canCalculate() {
      return this.number1 !== null && this.number2 !== null &&
             this.number1 !== '' && this.number2 !== '' &&
             !isNaN(this.number1) && !isNaN(this.number2)
    }
  },
  mounted() {
    this.updateMetaTags()
    this.updateSEO()
  },
  watch: {
    '$i18n.locale'() {
      this.updateMetaTags()
      this.updateSEO()
    },
    '$route'() {
      this.updateMetaTags()
      this.updateSEO()
    }
  },
  methods: {
    updateMetaTags() {
      const locale = this.$i18n.locale
      
      document.title = this.$t('calculators.longMultiplication.seo.title')
      
      let metaDescription = document.querySelector('meta[name="description"]')
      if (!metaDescription) {
        metaDescription = document.createElement('meta')
        metaDescription.setAttribute('name', 'description')
        document.head.appendChild(metaDescription)
      }
      metaDescription.setAttribute('content', this.$t('calculators.longMultiplication.seo.description'))
      
      let metaKeywords = document.querySelector('meta[name="keywords"]')
      if (!metaKeywords) {
        metaKeywords = document.createElement('meta')
        metaKeywords.setAttribute('name', 'keywords')
        document.head.appendChild(metaKeywords)
      }
      metaKeywords.setAttribute('content', this.$t('calculators.longMultiplication.seo.keywords'))
      
      document.documentElement.lang = locale
      
      this.updateOpenGraph()
    },
    updateOpenGraph() {
      const ogTitle = document.querySelector('meta[property="og:title"]') || document.createElement('meta')
      ogTitle.setAttribute('property', 'og:title')
      ogTitle.setAttribute('content', this.$t('calculators.longMultiplication.seo.title'))
      if (!document.querySelector('meta[property="og:title"]')) {
        document.head.appendChild(ogTitle)
      }
      
      const ogDescription = document.querySelector('meta[property="og:description"]') || document.createElement('meta')
      ogDescription.setAttribute('property', 'og:description')
      ogDescription.setAttribute('content', this.$t('calculators.longMultiplication.seo.description'))
      if (!document.querySelector('meta[property="og:description"]')) {
        document.head.appendChild(ogDescription)
      }

      const baseUrl = window.location.origin
      const ogUrl = document.querySelector('meta[property="og:url"]') || document.createElement('meta')
      ogUrl.setAttribute('property', 'og:url')
      ogUrl.setAttribute('content', baseUrl + this.$route.path)
      if (!document.querySelector('meta[property="og:url"]')) {
        document.head.appendChild(ogUrl)
      }
    },
    updateSEO() {
      updateHreflangTags(this.$route.path, supportedLocales)
      updateCanonicalTag(this.$route.path)
    },
    validateInput() {
      this.error = ''
    },
    performLongMultiplication(num1, num2) {
      const steps = []
      const str1 = Math.abs(num1).toString()
      const str2 = Math.abs(num2).toString()
      const multiplier = parseInt(str1)
      const multiplicand = parseInt(str2)
      const multiplierDigits = str1.split('').reverse().map(Number)
      const multiplicandDigits = str2.split('').reverse().map(Number)
      
      // Calculate each partial product
      const partialProducts = []
      multiplicandDigits.forEach((digit, index) => {
        const partialProduct = multiplier * digit
        const shifted = partialProduct * Math.pow(10, index)
        partialProducts.push({
          digit,
          partialProduct,
          shifted,
          index
        })
      })
      
      // Build step-by-step display
      const maxLength = Math.max(str1.length, str2.length, String(multiplier * multiplicand).length) + 2
      
      // Step 1: Show the multiplication setup
      let setupDisplay = `<div class="math-display">`
      setupDisplay += `<div class="math-line" style="text-align: right; padding: 0.25rem 0;">${str1}</div>`
      setupDisplay += `<div class="math-line" style="text-align: right; padding: 0.25rem 0;">× ${str2}</div>`
      setupDisplay += `<div class="math-line" style="border-top: 2px solid var(--border-color); padding-top: 0.5rem; margin-top: 0.25rem;"></div>`
      setupDisplay += `</div>`
      
      steps.push({
        display: setupDisplay,
        explanation: this.$t('calculators.longMultiplication.steps.setup')
      })
      
      // Step 2: Show each partial product
      partialProducts.forEach((pp, idx) => {
        if (pp.partialProduct > 0) {
          let stepDisplay = `<div class="math-display">`
          stepDisplay += `<div class="math-line" style="text-align: right; padding: 0.25rem 0;">${str1}</div>`
          stepDisplay += `<div class="math-line" style="text-align: right; padding: 0.25rem 0;">× ${str2}</div>`
          stepDisplay += `<div class="math-line" style="border-top: 2px solid var(--border-color); padding-top: 0.5rem; margin-top: 0.25rem;"></div>`
          
          // Show indentation for each partial product
          for (let i = 0; i < idx; i++) {
            stepDisplay += `<div class="math-line" style="text-align: right; padding: 0.25rem 0; color: transparent;">0</div>`
          }
          
          stepDisplay += `<div class="math-line" style="text-align: right; padding: 0.25rem 0; color: var(--primary-color); font-weight: 700;">${pp.partialProduct}</div>`
          
          if (idx < partialProducts.length - 1) {
            stepDisplay += `<div class="math-line" style="padding: 0.25rem 0; margin-top: 0.25rem; border-bottom: 1px dashed var(--border-light);"></div>`
          }
          
          stepDisplay += `</div>`
          
          steps.push({
            display: stepDisplay,
            explanation: this.$t('calculators.longMultiplication.steps.partialProduct', { 
              digit: pp.digit, 
              result: pp.partialProduct,
              position: idx + 1
            })
          })
        }
      })
      
      // Step 3: Show final addition and result
      const finalResult = multiplier * multiplicand
      let finalDisplay = `<div class="math-display">`
      finalDisplay += `<div class="math-line" style="text-align: right; padding: 0.25rem 0;">${str1}</div>`
      finalDisplay += `<div class="math-line" style="text-align: right; padding: 0.25rem 0;">× ${str2}</div>`
      finalDisplay += `<div class="math-line" style="border-top: 2px solid var(--border-color); padding-top: 0.5rem; margin-top: 0.25rem;"></div>`
      
      partialProducts.forEach((pp, idx) => {
        if (pp.partialProduct > 0) {
          const padding = '&nbsp;'.repeat(Math.max(0, String(finalResult).length - String(pp.shifted).length))
          finalDisplay += `<div class="math-line" style="text-align: right; padding: 0.25rem 0;">${padding}${pp.partialProduct}</div>`
        }
      })
      
      finalDisplay += `<div class="math-line" style="border-top: 2px solid var(--primary-color); padding-top: 0.5rem; margin-top: 0.25rem; text-align: right; font-weight: 700; color: var(--primary-color);">${finalResult}</div>`
      finalDisplay += `</div>`
      
      steps.push({
        display: finalDisplay,
        explanation: this.$t('calculators.longMultiplication.steps.finalResult', { result: finalResult })
      })
      
      return steps
    },
    calculate() {
      this.error = ''
      this.multiplicationSteps = []
      
      if (this.number1 === null || this.number2 === null ||
          this.number1 === '' || this.number2 === '' ||
          isNaN(this.number1) || isNaN(this.number2)) {
        this.error = this.$t('calculators.longMultiplication.error.invalidInput')
        return
      }

      const num1 = parseFloat(this.number1)
      const num2 = parseFloat(this.number2)
      
      // Check if numbers are integers
      if (!Number.isInteger(num1) || !Number.isInteger(num2)) {
        this.error = this.$t('calculators.longMultiplication.error.integersOnly')
        return
      }

      this.result = num1 * num2
      this.multiplicationSteps = this.performLongMultiplication(num1, num2)
    },
    clear() {
      this.number1 = null
      this.number2 = null
      this.result = null
      this.error = ''
      this.multiplicationSteps = []
    }
  }
}
</script>

<style scoped>
.calculator-page {
  min-height: 100vh;
  position: relative;
  background: var(--bg-secondary);
}

.page-background {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 0;
  overflow: hidden;
  pointer-events: none;
}

.bg-gradient {
  position: absolute;
  top: -50%;
  left: -50%;
  width: 200%;
  height: 200%;
  background: radial-gradient(circle at 30% 20%, rgba(99, 102, 241, 0.08) 0%, transparent 50%),
              radial-gradient(circle at 70% 80%, rgba(139, 92, 246, 0.08) 0%, transparent 50%);
  animation: gradientShift 20s ease infinite;
}

@keyframes gradientShift {
  0%, 100% { transform: translate(0, 0) rotate(0deg); }
  50% { transform: translate(5%, 5%) rotate(180deg); }
}

.container {
  position: relative;
  z-index: 1;
}

.calculator-header {
  text-align: center;
  padding: 3rem 0 2rem;
  position: relative;
}

.back-button {
  display: inline-flex;
  align-items: center;
  gap: 0.625rem;
  color: var(--text-primary);
  font-weight: 600;
  margin-bottom: 2rem;
  transition: all 0.3s ease;
  padding: 0.75rem 1.25rem;
  border-radius: 0.75rem;
  background: var(--bg-primary);
  border: 1px solid var(--border-light);
  box-shadow: var(--shadow-sm);
}

.back-button:hover {
  color: var(--primary-color);
  border-color: var(--primary-color);
  transform: translateX(-4px);
  box-shadow: var(--shadow-md);
}

.back-icon {
  width: 20px;
  height: 20px;
}

.header-content {
  max-width: 800px;
  margin: 0 auto;
}

.title-badge {
  display: inline-block;
  padding: 0.5rem 1.25rem;
  background: var(--gradient-primary);
  color: white;
  border-radius: 2rem;
  font-size: 0.875rem;
  font-weight: 700;
  letter-spacing: 0.5px;
  text-transform: uppercase;
  margin-bottom: 1.5rem;
  box-shadow: 0 4px 12px rgba(99, 102, 241, 0.3);
}

.page-title {
  font-size: 3.5rem;
  font-weight: 900;
  margin-bottom: 1.25rem;
  color: var(--text-primary);
  letter-spacing: -2px;
  line-height: 1.1;
}

.page-description {
  font-size: 1.25rem;
  color: var(--text-secondary);
  line-height: 1.7;
  max-width: 600px;
  margin: 0 auto;
}

.calculator-container {
  max-width: 1100px;
  margin: 0 auto;
  padding-bottom: 4rem;
}

.calculator-card {
  background: var(--bg-primary);
  border: 1px solid var(--border-light);
  border-radius: 2rem;
  padding: 3rem;
  box-shadow: var(--shadow-xl);
  backdrop-filter: blur(10px);
}

.input-section {
  margin-bottom: 2rem;
}

.input-row {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 1.5rem;
  margin-bottom: 2rem;
}

.input-card {
  background: linear-gradient(135deg, rgba(99, 102, 241, 0.03) 0%, rgba(139, 92, 246, 0.03) 100%);
  border: 2px solid var(--border-light);
  border-radius: 1.5rem;
  padding: 2.5rem;
  transition: all 0.3s ease;
}

.input-card:hover {
  border-color: var(--primary-color);
  box-shadow: 0 8px 24px rgba(99, 102, 241, 0.15);
}

.input-label {
  display: block;
  font-weight: 700;
  color: var(--text-primary);
  font-size: 1.125rem;
  margin-bottom: 1.5rem;
  text-align: center;
}

.number-input {
  width: 100%;
  padding: 1.5rem 2rem;
  border: 2px solid var(--border-color);
  border-radius: 1rem;
  font-size: 2rem;
  font-weight: 700;
  text-align: center;
  transition: all 0.3s ease;
  background: var(--bg-primary);
  color: var(--text-primary);
}

.number-input:focus {
  border-color: var(--primary-color);
  outline: none;
  box-shadow: 0 0 0 4px rgba(99, 102, 241, 0.1);
  transform: scale(1.02);
}

.action-buttons {
  display: flex;
  gap: 1rem;
  justify-content: center;
  flex-wrap: wrap;
}

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.75rem;
  padding: 1.125rem 2.5rem;
  border-radius: 0.875rem;
  font-size: 1.0625rem;
  font-weight: 700;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  border: none;
  cursor: pointer;
  font-family: inherit;
  min-width: 160px;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-icon {
  width: 22px;
  height: 22px;
}

.btn-primary {
  background: var(--gradient-primary);
  color: white;
  box-shadow: 0 4px 16px rgba(99, 102, 241, 0.4);
}

.btn-primary:hover:not(:disabled) {
  transform: translateY(-3px);
  box-shadow: 0 8px 24px rgba(99, 102, 241, 0.5);
}

.btn-secondary {
  background: var(--bg-secondary);
  color: var(--text-primary);
  border: 2px solid var(--border-color);
}

.btn-secondary:hover {
  background: var(--bg-tertiary);
  border-color: var(--primary-color);
  transform: translateY(-2px);
}

.slide-down-enter-active,
.slide-down-leave-active {
  transition: all 0.3s ease;
}

.slide-down-enter-from {
  opacity: 0;
  transform: translateY(-10px);
}

.error-message {
  display: flex;
  align-items: center;
  gap: 1rem;
  background: linear-gradient(135deg, #fee2e2 0%, #fecaca 100%);
  color: var(--error-color);
  padding: 1.5rem;
  border-radius: 1rem;
  font-weight: 600;
  margin-bottom: 2rem;
  border: 2px solid rgba(239, 68, 68, 0.2);
  box-shadow: 0 4px 12px rgba(239, 68, 68, 0.15);
}

.error-icon {
  width: 24px;
  height: 24px;
  flex-shrink: 0;
}

.slide-up-enter-active,
.slide-up-leave-active {
  transition: all 0.5s ease;
}

.slide-up-enter-from {
  opacity: 0;
  transform: translateY(20px);
}

.result-section {
  margin-top: 3rem;
  padding-top: 3rem;
  border-top: 2px solid var(--border-light);
}

.result-header {
  margin-bottom: 2.5rem;
  text-align: center;
}

.result-badge {
  display: inline-flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.875rem 2rem;
  background: var(--gradient-primary);
  color: white;
  border-radius: 2rem;
  font-size: 1.125rem;
  font-weight: 700;
  box-shadow: 0 4px 16px rgba(99, 102, 241, 0.3);
}

.result-icon {
  width: 24px;
  height: 24px;
}

.result-display {
  text-align: center;
  margin-bottom: 3rem;
  padding: 3rem 2rem;
  background: linear-gradient(135deg, rgba(99, 102, 241, 0.06) 0%, rgba(139, 92, 246, 0.06) 100%);
  border-radius: 1.5rem;
  border: 2px solid rgba(99, 102, 241, 0.15);
}

.multiplication-result {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 2rem;
}

.result-formula {
  display: flex;
  align-items: center;
  gap: 1.5rem;
  font-size: 2.5rem;
  font-weight: 700;
  flex-wrap: wrap;
  justify-content: center;
}

.formula-text {
  color: var(--text-primary);
}

.equals-sign {
  color: var(--text-secondary);
  font-weight: 400;
}

.result-value-box {
  padding: 1.5rem 3rem;
  background: white;
  border-radius: 1rem;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.result-value {
  font-size: 3rem;
  font-weight: 900;
  color: var(--primary-color);
  letter-spacing: -2px;
  line-height: 1;
}

.multiplication-steps-section {
  margin-top: 3rem;
  padding-top: 3rem;
  border-top: 2px solid var(--border-light);
}

.steps-header {
  display: flex;
  align-items: center;
  gap: 1rem;
  margin-bottom: 2rem;
  justify-content: center;
}

.steps-icon {
  width: 28px;
  height: 28px;
  color: var(--primary-color);
}

.steps-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--text-primary);
}

.multiplication-visualization {
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.multiplication-line {
  display: flex;
  gap: 1.5rem;
  align-items: flex-start;
  padding: 1.5rem;
  background: var(--bg-secondary);
  border-radius: 1rem;
  border: 1px solid var(--border-light);
}

.step-number {
  width: 36px;
  height: 36px;
  border-radius: 50%;
  background: var(--gradient-primary);
  color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 700;
  font-size: 1.125rem;
  flex-shrink: 0;
}

.step-content {
  flex: 1;
}

.multiplication-display {
  font-family: 'Courier New', monospace;
  font-size: 1.25rem;
  line-height: 1.8;
  color: var(--text-primary);
  background: white;
  padding: 1.5rem;
  border-radius: 0.75rem;
  border: 1px solid var(--border-light);
  margin-bottom: 1rem;
  overflow-x: auto;
}

.math-display {
  text-align: right;
  font-family: 'Courier New', monospace;
  min-width: 150px;
}

.math-line {
  font-size: 1.5rem;
  font-weight: 600;
  white-space: pre;
}

.step-explanation {
  font-size: 1.0625rem;
  line-height: 1.7;
  color: var(--text-secondary);
  padding-top: 0.25rem;
}

/* SEO Content Section */
.seo-content-section {
  margin-top: 4rem;
  max-width: 1100px;
  margin-left: auto;
  margin-right: auto;
}

.seo-content-card {
  background: var(--bg-primary);
  border: 1px solid var(--border-light);
  border-radius: 2rem;
  padding: 3.5rem;
  box-shadow: var(--shadow-xl);
}

.seo-heading {
  font-size: 2.5rem;
  font-weight: 800;
  color: var(--text-primary);
  margin-bottom: 2rem;
  letter-spacing: -1px;
  background: var(--gradient-primary);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.seo-paragraphs {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.seo-paragraph {
  font-size: 1.125rem;
  line-height: 1.9;
  color: var(--text-secondary);
  text-align: justify;
}

.seo-example {
  margin: 2rem 0;
  padding: 2rem;
  background: linear-gradient(135deg, rgba(99, 102, 241, 0.06) 0%, rgba(139, 92, 246, 0.06) 100%);
  border-radius: 1rem;
  border-left: 4px solid var(--primary-color);
}

.example-heading {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--text-primary);
  margin-bottom: 1rem;
  letter-spacing: -0.3px;
}

.example-text {
  font-size: 1.0625rem;
  line-height: 1.8;
  color: var(--text-secondary);
  margin: 0;
}

@media (max-width: 1024px) {
  .calculator-header {
    padding: 2rem 0 1.5rem;
  }

  .page-title {
    font-size: 2.75rem;
  }

  .calculator-card {
    padding: 2.5rem 2rem;
  }
}

@media (max-width: 768px) {
  .calculator-header {
    padding: 2rem 0 1.5rem;
  }
  
  .page-title {
    font-size: 2.25rem;
  }
  
  .page-description {
    font-size: 1.0625rem;
  }
  
  .calculator-card {
    padding: 2rem 1.5rem;
  }
  
  .input-row {
    grid-template-columns: 1fr;
  }
  
  .input-card {
    padding: 2rem 1.5rem;
  }
  
  .number-input {
    font-size: 1.75rem;
    padding: 1.25rem 1.5rem;
  }
  
  .result-value {
    font-size: 2.5rem;
  }
  
  .result-formula {
    font-size: 2rem;
  }
  
  .action-buttons {
    flex-direction: column;
  }
  
  .btn {
    width: 100%;
  }
  
  .multiplication-display {
    font-size: 1.125rem;
    padding: 1rem;
  }

  .math-line {
    font-size: 1.25rem;
  }
  
  .seo-content-card {
    padding: 2rem 1.5rem;
  }
  
  .seo-heading {
    font-size: 2rem;
  }
}

@media (max-width: 480px) {
  .calculator-header {
    padding: 1.5rem 0 1.25rem;
  }
  
  .page-title {
    font-size: 1.875rem;
  }
  
  .page-description {
    font-size: 1rem;
  }
  
  .calculator-card {
    padding: 1.5rem 1rem;
  }
}
</style>

// src/components-qwik/LongMultiplicationCalculator.tsx
import { component$, useSignal, useTask$, useVisibleTask$, $ } from '@builder.io/qwik';
import { Link, useLocation, type DocumentHead } from '@builder.io/qwik-city';
import { useTranslate } from '../i18n-qwik/useTranslate';
import { getWebAppSchema } from '../utils/webAppSchema';

export default component$(() => {
  const firstNumber = useSignal<number | null>(null);
  const secondNumber = useSignal<number | null>(null);
  const result = useSignal<number | null>(null);
  const error = useSignal<string | null>(null);
  const loc = useLocation();
  const t = useTranslate();
  
  const canCalculate = useSignal(false);
  
  useTask$(({ track }) => {
    track(() => firstNumber.value);
    track(() => secondNumber.value);
    canCalculate.value = 
      firstNumber.value !== null && firstNumber.value !== '' &&
      secondNumber.value !== null && secondNumber.value !== '';
  });
  
  const calculate = $(() => {
    error.value = null;
    result.value = null;
    
    if (!canCalculate.value) {
      return;
    }
    
    const a = parseFloat(String(firstNumber.value)) || 0;
    const b = parseFloat(String(secondNumber.value)) || 0;
    
    if (isNaN(a) || isNaN(b)) {
      error.value = t('calculators.longMultiplication.error.invalidInput');
      return;
    }
    
    try {
      const calculated = a * b;
      
      if (!isFinite(calculated)) {
        error.value = t('calculators.longMultiplication.error.invalidResult');
        return;
      }
      
      result.value = calculated;
    } catch (e) {
      error.value = t('calculators.longMultiplication.error.calculationError');
    }
  });
  
  const clear = $(() => {
    firstNumber.value = null;
    secondNumber.value = null;
    result.value = null;
    error.value = null;
  });
  
  const formatNumber = (value: number | null): string => {
    if (value === null || value === undefined || value === '') return '0';
    const num = parseFloat(String(value)) || 0;
    if (Math.abs(num) >= 1000) {
      return num.toLocaleString('en-US', { maximumFractionDigits: 10 });
    }
    return num.toString();
  };
  
  const formatResult = (value: number | null): string => {
    if (value === null || value === undefined) return '0';
    if (!isFinite(value)) return '∞';
    if (Math.abs(value) >= 1000) {
      return value.toLocaleString('en-US', { maximumFractionDigits: 10 });
    }
    return value.toLocaleString('en-US', { maximumFractionDigits: 2 });
  };
  
  const pathParts = loc.url.pathname.split('/').filter(p => p);
  const supportedLocales = ['en', 'pl', 'sv', 'de', 'es', 'fr', 'it', 'nl', 'pt', 'vi', 'tr', 'ru', 'fa', 'th', 'ja', 'zh'];
  const locale = pathParts[0] && supportedLocales.includes(pathParts[0]) ? pathParts[0] : 'en';
  const mathCalcPath = locale === 'en' ? '/calculators/math-calculators' : `/${locale}/calculators/math-calculators`;
  
  // Get calculator name and description for WebApplication schema
  const calculatorName = t('calculators.long-multiplication.title');
  const calculatorDescription = t('calculators.long-multiplication.seo.description');
  
  // Add WebApplication schema JSON-LD to head
  useVisibleTask$(() => {
    const webAppSchema = getWebAppSchema(locale, loc.url.href, calculatorName, calculatorDescription);
    
    const existingWebAppScript = document.querySelector('script[data-webapp-schema]');
    if (existingWebAppScript) {
      existingWebAppScript.remove();
    }
    
    const webAppScript = document.createElement('script');
    webAppScript.type = 'application/ld+json';
    webAppScript.setAttribute('data-webapp-schema', 'true');
    webAppScript.textContent = JSON.stringify(webAppSchema);
    document.head.appendChild(webAppScript);
  });

  return (
    <div class="calculator-page">
      <div class="page-background">
        <div class="bg-gradient"></div>
      </div>
      
      <div class="container">
        <div class="calculator-header">
          <Link href={mathCalcPath} class="back-button">
            <svg class="back-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M15 18L9 12L15 6" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            <span>{t('common.back')}</span>
          </Link>
          <div class="header-content">
            <div class="title-badge">{t('calculators.longMultiplication.badge')}</div>
            <h1 class="page-title">{t('calculators.longMultiplication.title')}</h1>
            <p class="page-description">{t('calculators.longMultiplication.description')}</p>
          </div>
        </div>
        
        <div class="calculator-container">
          <div class="calculator-card">
            <div class="input-section">
              <div class="addition-row">
                <div class="number-card">
                  <div class="number-card-header">
                    <div class="number-badge">×</div>
                    <label class="number-label">{t('calculators.longMultiplication.firstNumber')}</label>
                  </div>
                  <input
                    type="number"
                    class="number-input-large"
                    placeholder={t('calculators.longMultiplication.enterFirstNumber')}
                    value={firstNumber.value ?? ''}
                    onInput$={(e) => {
                      const target = e.target as HTMLInputElement;
                      firstNumber.value = target.value ? parseFloat(target.value) : null;
                    }}
                    onKeyUp$={(e) => {
                      if (e.key === 'Enter') {
                        calculate();
                      }
                    }}
                    step="any"
                  />
                </div>
                
                <div class="operator-card">
                  <div class="operator-symbol">×</div>
                </div>
                
                <div class="number-card">
                  <div class="number-card-header">
                    <div class="number-badge">×</div>
                    <label class="number-label">{t('calculators.longMultiplication.secondNumber')}</label>
                  </div>
                  <input
                    type="number"
                    class="number-input-large"
                    placeholder={t('calculators.longMultiplication.enterSecondNumber')}
                    value={secondNumber.value ?? ''}
                    onInput$={(e) => {
                      const target = e.target as HTMLInputElement;
                      secondNumber.value = target.value ? parseFloat(target.value) : null;
                    }}
                    onKeyUp$={(e) => {
                      if (e.key === 'Enter') {
                        calculate();
                      }
                    }}
                    step="any"
                  />
                </div>
              </div>
              
              {error.value && (
                <div class="error-message">
                  <svg class="error-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M12 8V12M12 16H12.01M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                  </svg>
                  <span>{error.value}</span>
                </div>
              )}
              
              <div class="action-buttons">
                <button onClick$={calculate} class="btn btn-primary" disabled={!canCalculate.value}>
                  <svg class="btn-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5 12H19M19 12L12 5M19 12L12 19" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                  </svg>
                  <span>{t('common.calculate')}</span>
                </button>
                <button onClick$={clear} class="btn btn-secondary">
                  <svg class="btn-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M18 6L6 18M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                  </svg>
                  <span>{t('common.clear')}</span>
                </button>
              </div>
            </div>
            
            {result.value !== null && !error.value && (
              <div class="result-section">
                <div class="result-header">
                  <div class="result-badge">
                    <svg class="result-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M9 12L11 14L15 10M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    {t('calculators.longMultiplication.result')}
                  </div>
                </div>
                
                <div class="result-display">
                  <div class="result-formula-large">
                    <div class="formula-number-box">
                      <span class="formula-number-value">{formatNumber(firstNumber.value)}</span>
                    </div>
                    <div class="formula-operator-box">
                      <span class="formula-operator-symbol">×</span>
                    </div>
                    <div class="formula-number-box">
                      <span class="formula-number-value">{formatNumber(secondNumber.value)}</span>
                    </div>
                    <div class="formula-equals-box">
                      <span class="formula-equals-symbol">=</span>
                    </div>
                    <div class="result-value-box-large">
                      <span class="result-value-large">{formatResult(result.value)}</span>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
          
          <div class="seo-content-section">
            <div class="seo-content-card">
              <h2 class="seo-heading">{t('calculators.longMultiplication.seo.content.heading')}</h2>
              
              <div class="seo-paragraphs">
                <p class="seo-paragraph">
                  {t('calculators.longMultiplication.seo.content.paragraph1')}
                </p>
                
                <p class="seo-paragraph">
                  {t('calculators.longMultiplication.seo.content.paragraph2')}
                </p>
                
                <p class="seo-paragraph">
                  {t('calculators.longMultiplication.seo.content.paragraph3')}
                </p>
                
                <div class="seo-example">
                  <h3 class="example-heading">{t('calculators.longMultiplication.seo.content.exampleHeading')}</h3>
                  <p class="example-text">{t('calculators.longMultiplication.seo.content.exampleText')}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
});

export const head: DocumentHead = ({ resolveValue }) => {
  const t = resolveValue(useTranslate);
  return {
    title: t('calculators.longMultiplication.seo.title'),
    meta: [
      {
        name: 'description',
        content: t('calculators.longMultiplication.seo.description'),
      },
      {
        name: 'keywords',
        content: t('calculators.longMultiplication.seo.keywords'),
      },
    ],
  };
};
